[package]
name = "actix-file-server-template"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.11.0"
shuttle-actix-web = "0.57.0"
shuttle-runtime = "0.57.0"
tokio = "1.48.0"
actix-web-httpauth = "0.8.2"
actix-files = "0.6.8"
